services:
  n8n:
    image: n8nio/n8n
    restart: always
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - D:/docker_data/n8n_data:/home/node/.n8n
      - D:/docker_data/shared:/data/shared
    networks:
      - n8n_ollama_net
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - PGHOST=pgvector-db
      - PGPORT=5432
      - PGDATABASE=n8n_db
      - PGUSER=langchain
      - PGPASSWORD=langchain
      - PGSSLMODE=require

  ollama:
    image: ollama/ollama
    restart: always
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - n8n_ollama_net
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - D:/docker_data/ollama_models:/root/.ollama

  pgvector-db:
    image: pgvector/pgvector:pg17-trixie
    restart: always
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_DB=n8n_db
    volumes:
      - D:/docker_data/pgvector_data:/var/lib/postgresql/data
    networks:
      - n8n_ollama_net

networks:
  n8n_ollama_net:
    driver: bridge

volumes:
  n8n_data:
  pgvector_data:
  ollama_models: